import type { ModelInfo } from './types';

export const modelsData: ModelInfo[] = [
	{
		name: 'Pony Diffusion V6 XL',
		platform: 'Community',
		category: 'Anime/Anthro',
		base: 'SDXL',
		downloads: '250.9M',
		rating: 4.8,
		specialty: 'Furry, Anime, Cartoon',
		hardware: '12GB+ VRAM',
		architecture: 'sdxl',
		style: 'anime',
		usecase: 'character',
		quality: 'production',
		modality: 'text-to-image',
		popularity_score: 250900000,
		trending_score: 85,
	},
	{
		name: 'Illustrious XL v1.1',
		platform: 'Community',
		category: 'Anime',
		base: 'SDXL',
		downloads: '82K',
		rating: 4.9,
		specialty: 'Character comprehension',
		hardware: '12GB+ VRAM',
		architecture: 'sdxl',
		style: 'anime',
		usecase: 'character',
		quality: 'production',
		modality: 'text-to-image',
		created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
		trending_score: 120,
	},
	{
		name: 'NoobAI-XL V-Pred',
		platform: 'Community',
		category: 'Anime',
		base: 'SDXL Custom',
		downloads: '3.3M',
		rating: 4.7,
		specialty: 'Comprehensive anime',
		hardware: '12GB+ VRAM',
		architecture: 'sdxl',
		style: 'anime',
		usecase: 'character',
		quality: 'production',
		modality: 'text-to-image',
		popularity_score: 3300000,
	},
	{
		name: 'Realistic Vision V6.0',
		platform: 'Community',
		category: 'Realistic',
		base: 'SDXL',
		downloads: '45.2M',
		rating: 4.6,
		specialty: 'Photorealistic images',
		hardware: '8GB+ VRAM',
		architecture: 'sdxl',
		style: 'realistic',
		usecase: 'portrait',
		quality: 'standard',
		modality: 'text-to-image',
		popularity_score: 45200000,
	},
	{
		name: 'FLUX.1 Dev',
		platform: 'Community',
		category: 'Open Source',
		base: 'FLUX',
		rating: 4.7,
		specialty: 'Open source excellence',
		hardware: 'Cloud/Local',
		architecture: 'flux',
		style: 'artistic',
		usecase: 'concept',
		quality: 'standard',
		modality: 'text-to-image',
		created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days ago
	},
];

export const platformData = undefined; 