import type { ModelInfo } from './types';

export const modelsData: ModelInfo[] = [
	{
		name: 'Pony Diffusion V6 XL',
		platform: 'Civitai',
		category: 'Anime/Anthro',
		base: 'SDXL',
		downloads: '250.9M',
		rating: 4.8,
		specialty: 'Furry, Anime, Cartoon',
		hardware: '12GB+ VRAM',
		architecture: 'sdxl',
		style: 'anime',
		usecase: 'character',
		quality: 'production',
	},
	{
		name: 'Illustrious XL v1.1',
		platform: 'Civitai',
		category: 'Anime',
		base: 'SDXL',
		downloads: '82K',
		rating: 4.9,
		specialty: 'Character comprehension',
		hardware: '12GB+ VRAM',
		architecture: 'sdxl',
		style: 'anime',
		usecase: 'character',
		quality: 'production',
	},
	{
		name: 'NoobAI-XL V-Pred',
		platform: 'Civitai',
		category: 'Anime',
		base: 'SDXL Custom',
		downloads: '3.3M',
		rating: 4.7,
		specialty: 'Comprehensive anime',
		hardware: '12GB+ VRAM',
		architecture: 'sdxl',
		style: 'anime',
		usecase: 'character',
		quality: 'production',
	},
	{
		name: 'Imagen4 Preview',
		platform: 'Fal.ai',
		category: 'Commercial',
		base: 'Proprietary',
		api_cost: '$0.05/image',
		rating: 4.9,
		specialty: 'Highest quality',
		hardware: 'Cloud only',
		architecture: 'proprietary',
		style: 'realistic',
		usecase: 'concept',
		quality: 'production',
	},
	{
		name: 'FLUX.1 Kontext Pro',
		platform: 'Fal.ai',
		category: 'Professional',
		base: 'FLUX',
		api_cost: '$0.03/image',
		rating: 4.8,
		specialty: 'Reference-guided editing',
		hardware: 'Cloud only',
		architecture: 'flux',
		style: 'realistic',
		usecase: 'concept',
		quality: 'production',
	},
	{
		name: 'Veo 3',
		platform: 'Fal.ai',
		category: 'Video',
		base: 'Proprietary',
		api_cost: '$0.50/video',
		rating: 4.9,
		specialty: 'Cinematic video',
		hardware: 'Cloud only',
		architecture: 'proprietary',
		style: 'realistic',
		usecase: 'concept',
		quality: 'production',
	},
	{
		name: 'Realistic Vision V6.0',
		platform: 'Civitai',
		category: 'Realistic',
		base: 'SDXL',
		downloads: '45.2M',
		rating: 4.6,
		specialty: 'Photorealistic images',
		hardware: '8GB+ VRAM',
		architecture: 'sdxl',
		style: 'realistic',
		usecase: 'portrait',
		quality: 'standard',
	},
	{
		name: 'FLUX.1 Dev',
		platform: 'Fal.ai',
		category: 'Open Source',
		base: 'FLUX',
		api_cost: '$0.02/image',
		rating: 4.7,
		specialty: 'Open source excellence',
		hardware: 'Cloud/Local',
		architecture: 'flux',
		style: 'artistic',
		usecase: 'concept',
		quality: 'standard',
	},
];

export const platformData = {
	labels: [
		'Community Models',
		'API Infrastructure',
		'Anime/Manga Models',
		'Commercial Models',
		'Training Tools',
		'Speed',
		'Cost Effectiveness',
		'Customization',
		'Reliability',
		'Model Variety',
	],
	datasets: [
		{
			label: 'Civitai',
			data: [10, 4, 9, 3, 6, 6, 9, 10, 7, 9],
			backgroundColor: '#3B82F6',
			borderColor: '#3B82F6',
			borderWidth: 1,
		},
		{
			label: 'Fal.ai',
			data: [3, 10, 4, 10, 8, 9, 6, 5, 9, 7],
			backgroundColor: '#F97316',
			borderColor: '#F97316',
			borderWidth: 1,
		},
	],
}; 